package ablam;

import java.sql.*;

public class BookRepository {
    private Connection c;

    public BookRepository(){
        DBConnector connector = new DBConnector();
        c = connector.connect();
    }

    public void actualInsert(String statement) throws SQLException {
        Statement stmt = c.createStatement();
        stmt.executeUpdate(statement);

        c.close();
    }
    public String actualSelect(String statement) throws SQLException {
        Statement stmt = c.createStatement();
        ResultSet rs = stmt.executeQuery(statement);

        c.close();
        return resultSetToString(rs);
    }

    /**
     * This method transforms answer from database into string that we will print out later
     * @param rs ResultSet that we got after making a select request
     * @return String, that was generated by ResultSet we got
     */
    public String resultSetToString(ResultSet rs){
        StringBuilder infoToPrint = new StringBuilder();
        try{
            while(rs.next()){
                infoToPrint.append("title: ");
                infoToPrint.append(rs.getString(1));
                infoToPrint.append(" author: ");
                infoToPrint.append(rs.getString(2));
                infoToPrint.append(" published in: ");
                infoToPrint.append(rs.getString(3));
                infoToPrint.append("\n");
            }
        } catch (SQLException e){
            System.out.println(e.getMessage());
        }
        return infoToPrint.toString();
    }

    private class DBConnector implements Connector{
        private final String url = "jdbc:postgresql://localhost/ablam";
        private final String user = "ablam";
        private final String password = "delamland";

        public Connection connect() {
            Connection conn = null;
            try {
                conn = DriverManager.getConnection(url, user, password);
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
            return conn;
        }
    }
}


